feat(asdf): asdf

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,7 +16,9 @@ concurrency:
 
 jobs:
   build:
+    name: Build
     runs-on: ubuntu-latest
+    environment: content
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -30,15 +32,21 @@ jobs:
       - name: Install Dependencies
         run: npm ci
 
-      - name: Generate JSON files from GitHub Environment
+      - name: Generate files
         env:
-          SECTIONS_DATA: ${{ vars.MY_SECTIONS_JSON }}
-          # SETTINGS_DATA: ${{ vars.MY_SETTINGS_JSON }}
+          MANIFEST: ${{ vars.MANIFEST }}
+          ALL_VARS: ${{ toJSON(vars) }}
         run: |
-          mkdir -p public/data
-          
-          echo "$SECTIONS_DATA" > public/data/sections.json
-          echo "${SETTINGS_DATA:-{}}" > public/data/settings.json
+          mkdir -p src/data
+          [ ! -z "$MANIFEST" ] || { echo "Not found MANIFEST in GitHub"; exit 1; }
+          echo "$MANIFEST" | jq -c '.[]' | while read item; do
+            filepath=$(echo "$item" | jq -r '.filepath')
+            env_key=$(echo "$item" | jq -r '.env_key')
+            content=$(echo "$ALL_VARS" | jq -r ".[\"$env_key\"] // empty")
+            [ -n "$content" ] || { echo "Not found $env_key"; continue; }
+            mkdir -p "$(dirname "src/data/$filepath")"
+            echo "$content" > "src/data/$filepath"
+          done
 
       - name: Build Project
         run: npm run build
@@ -51,12 +59,12 @@ jobs:
           path: ./dist
 
   deploy:
+    name: Deploy
+    runs-on: ubuntu-latest
+    needs: build
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
-    needs: build
-    runs-on: ubuntu-latest
-    name: Deploy
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
